version: '3.4'

services:
  todoapi:
    container_name: todosApi
    image: ${DOCKER_REGISTRY-}todoapi
    build:
      context: .
      dockerfile: TodoList/Dockerfile
    depends_on:
      todoDatabase:
        condition: service_healthy
    ports:
      - 8080:8080
      - 8081:8081

  todoDatabase:
    image: postgres:latest
    container_name: todosDatabase
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todos
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready'"]
      interval: 10s
      timeout: 3s
      retries: 3
